/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PropertyManagementRouteImport } from './routes/property-management'
import { Route as MeetMaryleneRouteImport } from './routes/meet-marylene'
import { Route as LaRivieraRouteImport } from './routes/la-riviera'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyManagementRoute = PropertyManagementRouteImport.update({
  id: '/property-management',
  path: '/property-management',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetMaryleneRoute = MeetMaryleneRouteImport.update({
  id: '/meet-marylene',
  path: '/meet-marylene',
  getParentRoute: () => rootRouteImport,
} as any)
const LaRivieraRoute = LaRivieraRouteImport.update({
  id: '/la-riviera',
  path: '/la-riviera',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/films': typeof FilmsRoute
  '/la-riviera': typeof LaRivieraRoute
  '/meet-marylene': typeof MeetMaryleneRoute
  '/property-management': typeof PropertyManagementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/films': typeof FilmsRoute
  '/la-riviera': typeof LaRivieraRoute
  '/meet-marylene': typeof MeetMaryleneRoute
  '/property-management': typeof PropertyManagementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/films': typeof FilmsRoute
  '/la-riviera': typeof LaRivieraRoute
  '/meet-marylene': typeof MeetMaryleneRoute
  '/property-management': typeof PropertyManagementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/films'
    | '/la-riviera'
    | '/meet-marylene'
    | '/property-management'
    | '/sitemap.xml'
    | '/portfolio/$slug'
    | '/properties/$slug'
    | '/portfolio/'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/films'
    | '/la-riviera'
    | '/meet-marylene'
    | '/property-management'
    | '/sitemap.xml'
    | '/portfolio/$slug'
    | '/properties/$slug'
    | '/portfolio'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/films'
    | '/la-riviera'
    | '/meet-marylene'
    | '/property-management'
    | '/sitemap.xml'
    | '/portfolio/$slug'
    | '/properties/$slug'
    | '/portfolio/'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FilmsRoute: typeof FilmsRoute
  LaRivieraRoute: typeof LaRivieraRoute
  MeetMaryleneRoute: typeof MeetMaryleneRoute
  PropertyManagementRoute: typeof PropertyManagementRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-management': {
      id: '/property-management'
      path: '/property-management'
      fullPath: '/property-management'
      preLoaderRoute: typeof PropertyManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-marylene': {
      id: '/meet-marylene'
      path: '/meet-marylene'
      fullPath: '/meet-marylene'
      preLoaderRoute: typeof MeetMaryleneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-riviera': {
      id: '/la-riviera'
      path: '/la-riviera'
      fullPath: '/la-riviera'
      preLoaderRoute: typeof LaRivieraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FilmsRoute: FilmsRoute,
  LaRivieraRoute: LaRivieraRoute,
  MeetMaryleneRoute: MeetMaryleneRoute,
  PropertyManagementRoute: PropertyManagementRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
